### ISSUE TITLE
Notification about new thread in sub-forum disappears if another thread in the same sub-forum visited.

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#39] opened 2020-02-26 09:51 UTC
Requires some checking, as it could be my accidental fail.

**Describe the bug**
If you subscribed to sub-forum, you receive a notification about new threads. While notification should disappear only when you visit thread or sub-forum page, it also dissapears, when you visit any different thread in this sub-forum (e.q. from another notification)

**Expected behavior**
Keep notification until I visit thread or sub-forum front page.

**Comment by liamwhite** [comment] 2020-03-07 18:26
It is, as far as I know, not possible to dismiss new topic notifications without visiting the forum page. Closing, since no steps to reproduce are given, I can't reproduce locally, and no other user reports exist.

**Comment by stsyn** [comment] 2020-07-02 14:01
Reproduced again. Subscribe to both thread in subforum (1) and for subforum itself (2), then receive notification for both, and then reading thread in 1st notify omits both notifications.
Also only one notification for new thread per forum (not subforum, **whole forum**) can present.

**Comment by parasprite** [comment] 2020-10-25 00:31
Steps to reproduce:

1. Subscribe to thread A
2. Use the subscribe button on the subforum (for new threads)
3. Create thread B and reply on thread A with another account
4. Notifications show for thread A and thread B
5. Visit thread A (thread that was replied to)
6. Both thread A and thread B disappear from notifications

Expected behavior: Thread B remains in notifications.

**Closed** 2020-10-27 02:30 UTC
Labels: bug
