### ISSUE TITLE
User links attempt to assign badge where none exists

### ISSUE THREAD

**Issue by almafeta** [derpibooru/philomena#128] opened 2020-06-06 19:56 UTC
**Describe the bug**
The installation process doesn't create any badges.

https://github.com/derpibooru/philomena/blob/9c7bbc127b6e2a7cbfd97101f6d7946a7f65cc3f/lib/philomena/user_links.ex#L94 is hardcoded to assign a badge named "Artist"

So, if you don't manually create that badge, then you attempt to create a user link, it will fail.

**Expected behavior**
Installation creates badge, "Artist", automatically.

**Comment by liamwhite** [comment] 2020-06-06 20:25
Do you mean in this report only that it doesn't assign awards? I haven't noticed any failure to accept user links in dev without having the artist badge present (it simply isn't assigned).

**Comment by liamwhite** [comment] 2020-06-16 16:58
Can you please clarify what the problem is here? Otherwise I will just close this.

**Closed** 2020-08-11 05:44 UTC
Labels: bug
